// network:host is forbidden

version: '3.9'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    hostname: localhost
    ports:
      - 443:443

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    hostname: localhost
    env_file: .env