version: '3.9'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    hostname: localhost
    ports:
      - 443:443
    volumes:
      - wp:/var/www/html/wordpress
    restart: always
    networks:
      - project

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    restart: always
    hostname: localhost
    env_file: .env
    volumes:
      - wp:/var/www/html
    networks:
      - project

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    restart: always
    env_file: .env
    volumes:
      - db:/var/lib/mysql
    networks:
      - project

  networks:
    project:
      driver: bridge

    volumes:
      wp:
        driver: local
        driver_opts:
          type: none
          device: /home/jlebre/data/wordpress
          o: bind
      db:
        driver: local
        driver_opts:
          type: none
          device: /home/jlebre/data/mysql
          o: bind