###################
#                 #
# DOCKER-COMPOSE  #
#                 #
###################

version: "3.8"
#───────────────────────────────────────────────────────────────────────#
# Version of Docker Compose. Check it with "docker-compose --version".  #  
#_______________________________________________________________________#

networks:
  project:
    name: project
    driver: bridge
#───────────────────────────────────────────────────────────────────────#
# Defines a costum network named 'project' with bridge driver.          #
# A network in Docker provides communication between containers.        #
# The 'bridge' driver is the default network driver for Docker,         #
# enabling communication between containers on the same host.           #
#_______________________________________________________________________#

volumes:
  wp:
    driver: local
    name: wp
    driver_opts:
      type: none
      o: bind
      device: home/jlebre/data/wp
  db:
    driver: local
    name: db
    driver_opts:
      type: none
      o: bind
      device: home/jlebre/data/db
#───────────────────────────────────────────────────────────────────────#
# Defines two volumes 'wp' and 'db' for persisting data.                #
# "db" is a volume that contains Wordpress database.                    #
# "wp" is a volume that contains Wordpress website files.               #
#_______________________________________________________________________#

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql
    networks:
      - project
    restart: always
#───────────────────────────────────────────────────────────────────────#
# MariaDB is a popular open-source relational database management       #
# system. In this context, it's a Docker service that provides          #
# a MariaDB database server.                                            #
#_______________________________________________________________________#

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - wp:/var/www/html
    networks:
      - project
    restart: always
#───────────────────────────────────────────────────────────────────────#
# WordPress is a popular open-source content management system. In this #
# context, it's a Docker service representing a WordPress website.      #
#_______________________________________________________________________#

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wp:/var/www/html
    networks:
      - project
    restart: always
#───────────────────────────────────────────────────────────────────────#
# Nginx is a popular open-source web server and reverse proxy server. In#
# this context, it's a Docker service representing an Nginx server that #
# serves the WordPress website.                                         #
#_______________________________________________________________________#

###################
#                 #
#     jlebre      #
#                 #
###################