version: "3.8"

services:

  nginx:
    build: ./requirements/nginx
    restart: on-failure
    ports:
      - 443:443
    volumes:
      - wp:/var/www/html
    depends_on:
      - mariadb
      - wordpress
    networks:
      - project

  wordpress:
    build: ./requirements/wordpress
    restart: on-failure
    depends_on:
      - mariadb
    env_file: .env
    volumes:
      - wp:/var/www/html
    networks:
      - project

  mariadb:
    build: ./requirements/mariadb
    restart: on-failure
    env_file: .env
    volumes:
      - db:/var/lib/mysql
    networks:
      - project

networks:
  project:
    driver: bridge

volumes:
  wp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jlebre/data/wp
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jlebre/data/db