echo "CREATE DATABASE IF NOT EXISTS \${DATABASE_NAME};" > DB.sql
echo "CREATE USER IF NOT EXISTS '\${MYSQL_USER}'@'%' IDENTIFIED BY '\${MYSQL_PASSWORD}';" >> DB.sql
echo "GRANT ALL PRIVILEGES ON \${DATABASE_NAME}.* TO '\${MYSQL_USER}'@'%';" >> DB.sql
echo "FLUSH PRIVILEGES;" >> DB.sql
echo >> DB.sql
echo "ALTER USER 'root'@'localhost' IDENTIFIED BY '\${MYSQL_ROOT_PASSWORD}';" >> DB.sql

exec "$@"